Repository criszz77/luna, pull requests merged in 2021-11, with the labels that each got.

#25 Remove typeRoots and update tsconfig.json template
  template/tsconfig.json
Labels: enhancement

#30 fix(android): android 12 compatibility
  template/android/app/src/debug/AndroidManifest.xml
  template/android/app/src/main/AndroidManifest.xml
  template/android/build.gradle
  template/android/gradle/wrapper/gradle-wrapper.jar
  template/android/gradle/wrapper/gradle-wrapper.properties
  template/android/gradlew
Labels: enhancement

#29 fix(paths): use directory-relative paths
  template/src/app/App.tsx
  template/src/app/components/LearnMoreLinks/LearnMoreLinks.tsx
  template/src/app/navigation/pages/Details/Details.tsx
  template/src/app/navigation/pages/Home/Home.tsx
Labels: bug

#31 docs(README): no longer contains elements, link to icons readme
  template/README.md
Labels: documentation

#32 Converge with upstream (react-native-typescript-template, and react-native/template)
  template/.eslintrc.js
  template/.prettierrc.js
  template/package.json
  template/patches/react-native+0.66.3.patch
  template/src/app/App.tsx
  template/src/app/components/DebugInstructions/DebugInstructions.tsx
  template/src/app/components/DebugInstructions/package.json
  template/src/app/components/Header/Header.tsx
  template/src/app/components/Header/package.json
  template/src/app/components/LearnMoreLinks/LearnMoreLinks.tsx
  template/src/app/components/LearnMoreLinks/package.json
  template/src/app/components/Section/Section.tsx
  template/src/app/components/Section/package.json
  template/src/app/components/StyledText.tsx
  template/src/app/components/components.tsx
  template/src/app/components/package.json
  template/src/app/hooks/useColors.ts
  template/src/app/navigation/TopTabNavigator.tsx
  template/src/app/navigation/package.json
  template/src/app/navigation/pages/Details/Details.tsx
  template/src/app/navigation/pages/Details/package.json
  template/src/app/navigation/pages/Home/Home.tsx
  template/src/app/navigation/pages/Home/package.json
  template/src/app/navigation/pages/package.json
  template/src/app/navigation/pages/pages.tsx
  template/src/app/package.json
  template/src/index.js
  template/src/static/assets/logo.png
  template/src/static/constants.tsx
  template/src/static/package.json
  template/src/types/links.d.ts
  template/src/utils/icons.js
Labels: enhancement
